# Reference: https://graspingtech.com/docker-compose-postgresql
version: '3.2'

services:
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=city_list_local

  city-list-api:
    build:
      context: ..
      dockerfile: deployment/dockerfile/Dockerfile-api
    links:
      - database
    ports:
      - ${API_PORT}:8080
    environment:
      SPRING_CONFIG_ADDITIONALLOCATION: file:/config/application.yml
      TEST_DB_USER: postgres
      TEST_DB_PASS: postgres
      TEST_DB_NAME: city_list_local
      ALLOWED_ORIGIN: http://${HOST}:${WEB_CLIENT_PORT}
    volumes:
      - ./configs/api/:/config/
      - ./downloads:/downloads

  city-list-web-client:
    build:
      context: ../city-list-web-client
      dockerfile: ../deployment/dockerfile/Dockerfile-web-client
      args:
        REACT_APP_API_BASE_URL: http://${HOST}:4080/api
    ports:
      - ${WEB_CLIENT_PORT}:80
