spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/city_list_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
    contexts: ${spring.profiles.active}
springdoc:
  swagger-ui:
    path: /documentation
