
spring:
  profiles:
    active: dev, cityInitializer
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/city_list_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
    contexts: ${spring.profiles.active}
springdoc:
  swagger-ui:
    path: /documentation

logging:
  level:
    com.maemresen.city.list: DEBUG

app:
  batch:
    csv-city-import:
      photo-download-retry:
        maxAttempts: 3
        maxDelay: 1000
  security:
    jwt:
      secret: jwt-secret-key
      expiration-ms: 86400000
server:
  servlet:
    context-path: /api
