server:
  port: 9000
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
app:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
    contexts: ${spring.profiles.active}
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/city_list_local
    driver: org.postgresql.Driver
    username: postgres
    password: postgres

jakarta:
  persistence:
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/city_list_local
      user: postgres
      password: postgres
logging:
  level:
    com.maemresen.city.list: DEBUG
