spring:
  profiles:
    active: dev, cityInitializer
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/city_list_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
    contexts: ${spring.profiles.active}

logging:
  level:
    com.maemresen.city.list: DEBUG

app:
  batch:
    csv-city-import:
      photo-download-retry:
        maxAttempts: 3
        maxDelay: 1000
  file-server:
    download-path: downloads
  security:
    cors:
      allow-credentials: true
      allowed-headers:
        - '*'
      allowed-origins:
        - http://localhost:3000
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
    paths:
      public-paths:
        all:
          - /v3/api-docs/**
          - /swagger-ui/**
          - /swagger-ui.html
        by-http-method:
          POST:
            - /auth/sign-in
            - /auth/refresh-token
          GET:
            - /file/**
    jwt:
      secret: jwt-secret-key
      access-token-expiration-ms: 3600000
      refresh-token-expiration-ms: 86400000
server:
  servlet:
    context-path: /api
