server:
  servlet:
    context-path: /api
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://database:5432/${TEST_DB_NAME}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASS}

app:
  security:
    cors:
      allowed-origins:
        - ${ALLOWED_ORIGIN}
