name: api
on: [ push, workflow_dispatch ]

env:
  MODULE_NAME: city-list-api
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - '${{ env.MODULE_NAME }}/**'  

  maven-build:
    if: ${{ (github.event_name == 'workflow_dispatch') || (needs.changes.outputs.changed == 'true') }}
    runs-on: ubuntu-latest
    needs:
      - changes
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean install -U -f ${{ env.MODULE_NAME }}/pom.xml
